name: Mathew Slavica
favicon: null
layout_spectrum: 0.5159692328888923
typography_spectrum: 0.22324736090376973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3368231251370162
  lightness: 0.81996671971865
  saturation: 0.2512729540467262
  rhythmicContrast: 0.6210135561414063
purpose: []
